//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace RutasFtp.PS.ServicioITA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IServicioIntegrador", Namespace="http://tempuri.org/")]
    public partial class ServicioIntegrador : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultarNotificadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarModulosOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarGrupoUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioIntegrador() {
            this.Url = global::RutasFtp.PS.Properties.Settings.Default.RutasFtp_PS_ServicioITA_ServicioIntegrador;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultarNotificadosCompletedEventHandler consultarNotificadosCompleted;
        
        /// <remarks/>
        public event consultarModulosCompletedEventHandler consultarModulosCompleted;
        
        /// <remarks/>
        public event consultarGrupoUsuarioCompletedEventHandler consultarGrupoUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioIntegrador/consultarNotificados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] consultarNotificados([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idApp) {
            object[] results = this.Invoke("consultarNotificados", new object[] {
                        idApp});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarNotificadosAsync(string idApp) {
            this.consultarNotificadosAsync(idApp, null);
        }
        
        /// <remarks/>
        public void consultarNotificadosAsync(string idApp, object userState) {
            if ((this.consultarNotificadosOperationCompleted == null)) {
                this.consultarNotificadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarNotificadosOperationCompleted);
            }
            this.InvokeAsync("consultarNotificados", new object[] {
                        idApp}, this.consultarNotificadosOperationCompleted, userState);
        }
        
        private void OnconsultarNotificadosOperationCompleted(object arg) {
            if ((this.consultarNotificadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarNotificadosCompleted(this, new consultarNotificadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioIntegrador/consultarModulos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/IntegradorAPP.PS.Servicios")]
        public Modulo[] consultarModulos([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idApp) {
            object[] results = this.Invoke("consultarModulos", new object[] {
                        usuario,
                        idApp});
            return ((Modulo[])(results[0]));
        }
        
        /// <remarks/>
        public void consultarModulosAsync(string usuario, string idApp) {
            this.consultarModulosAsync(usuario, idApp, null);
        }
        
        /// <remarks/>
        public void consultarModulosAsync(string usuario, string idApp, object userState) {
            if ((this.consultarModulosOperationCompleted == null)) {
                this.consultarModulosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarModulosOperationCompleted);
            }
            this.InvokeAsync("consultarModulos", new object[] {
                        usuario,
                        idApp}, this.consultarModulosOperationCompleted, userState);
        }
        
        private void OnconsultarModulosOperationCompleted(object arg) {
            if ((this.consultarModulosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarModulosCompleted(this, new consultarModulosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioIntegrador/consultarGrupoUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GrupoUsuario consultarGrupoUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idApp) {
            object[] results = this.Invoke("consultarGrupoUsuario", new object[] {
                        usuario,
                        idApp});
            return ((GrupoUsuario)(results[0]));
        }
        
        /// <remarks/>
        public void consultarGrupoUsuarioAsync(string usuario, string idApp) {
            this.consultarGrupoUsuarioAsync(usuario, idApp, null);
        }
        
        /// <remarks/>
        public void consultarGrupoUsuarioAsync(string usuario, string idApp, object userState) {
            if ((this.consultarGrupoUsuarioOperationCompleted == null)) {
                this.consultarGrupoUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarGrupoUsuarioOperationCompleted);
            }
            this.InvokeAsync("consultarGrupoUsuario", new object[] {
                        usuario,
                        idApp}, this.consultarGrupoUsuarioOperationCompleted, userState);
        }
        
        private void OnconsultarGrupoUsuarioOperationCompleted(object arg) {
            if ((this.consultarGrupoUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarGrupoUsuarioCompleted(this, new consultarGrupoUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/IntegradorAPP.PS.Servicios")]
    public partial class Modulo {
        
        private string pAppField;
        
        private int pOidField;
        
        private bool pOidFieldSpecified;
        
        private int pOrdenMostradoField;
        
        private bool pOrdenMostradoFieldSpecified;
        
        private string pRutaPadreField;
        
        private string pTextoNodoField;
        
        private string pUrlNodoField;
        
        private string pValorModuloField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pApp {
            get {
                return this.pAppField;
            }
            set {
                this.pAppField = value;
            }
        }
        
        /// <comentarios/>
        public int pOid {
            get {
                return this.pOidField;
            }
            set {
                this.pOidField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pOidSpecified {
            get {
                return this.pOidFieldSpecified;
            }
            set {
                this.pOidFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public int pOrdenMostrado {
            get {
                return this.pOrdenMostradoField;
            }
            set {
                this.pOrdenMostradoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pOrdenMostradoSpecified {
            get {
                return this.pOrdenMostradoFieldSpecified;
            }
            set {
                this.pOrdenMostradoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pRutaPadre {
            get {
                return this.pRutaPadreField;
            }
            set {
                this.pRutaPadreField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pTextoNodo {
            get {
                return this.pTextoNodoField;
            }
            set {
                this.pTextoNodoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pUrlNodo {
            get {
                return this.pUrlNodoField;
            }
            set {
                this.pUrlNodoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pValorModulo {
            get {
                return this.pValorModuloField;
            }
            set {
                this.pValorModuloField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/IntegradorAPP.PS.Servicios")]
    public partial class GrupoUsuario {
        
        private string pAppField;
        
        private bool pEscribirField;
        
        private bool pEscribirFieldSpecified;
        
        private bool pLeerField;
        
        private bool pLeerFieldSpecified;
        
        private bool pModificarField;
        
        private bool pModificarFieldSpecified;
        
        private string pNombreField;
        
        private int pOidField;
        
        private bool pOidFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pApp {
            get {
                return this.pAppField;
            }
            set {
                this.pAppField = value;
            }
        }
        
        /// <comentarios/>
        public bool pEscribir {
            get {
                return this.pEscribirField;
            }
            set {
                this.pEscribirField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pEscribirSpecified {
            get {
                return this.pEscribirFieldSpecified;
            }
            set {
                this.pEscribirFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool pLeer {
            get {
                return this.pLeerField;
            }
            set {
                this.pLeerField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pLeerSpecified {
            get {
                return this.pLeerFieldSpecified;
            }
            set {
                this.pLeerFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool pModificar {
            get {
                return this.pModificarField;
            }
            set {
                this.pModificarField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pModificarSpecified {
            get {
                return this.pModificarFieldSpecified;
            }
            set {
                this.pModificarFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pNombre {
            get {
                return this.pNombreField;
            }
            set {
                this.pNombreField = value;
            }
        }
        
        /// <comentarios/>
        public int pOid {
            get {
                return this.pOidField;
            }
            set {
                this.pOidField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pOidSpecified {
            get {
                return this.pOidFieldSpecified;
            }
            set {
                this.pOidFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void consultarNotificadosCompletedEventHandler(object sender, consultarNotificadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarNotificadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarNotificadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void consultarModulosCompletedEventHandler(object sender, consultarModulosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarModulosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarModulosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Modulo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Modulo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void consultarGrupoUsuarioCompletedEventHandler(object sender, consultarGrupoUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarGrupoUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarGrupoUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GrupoUsuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GrupoUsuario)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591