//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Bancos.PS.ServicioRecaudo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IRecaudo", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Recaudo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ServicioRecaudoDiarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Recaudo() {
            this.Url = global::Bancos.PS.Properties.Settings.Default.Bancos_PS_ServicioRecaudo_Recaudo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ServicioRecaudoDiarioCompletedEventHandler ServicioRecaudoDiarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRecaudo/ServicioRecaudoDiario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServicioRecaudoDiario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string NombreBanco, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string IdCuentaBanco, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string IdCuentaBancoEpicor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RutaEntrada, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RutaSalida, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] object[] CorreosControl, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Remitente, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string CodigoTransito, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string NumCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TipoCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RutaProcesados, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TipoProceso) {
            object[] results = this.Invoke("ServicioRecaudoDiario", new object[] {
                        NombreBanco,
                        IdCuentaBanco,
                        IdCuentaBancoEpicor,
                        RutaEntrada,
                        RutaSalida,
                        CorreosControl,
                        Remitente,
                        CodigoTransito,
                        NumCuenta,
                        TipoCuenta,
                        Usuario,
                        RutaProcesados,
                        TipoProceso});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ServicioRecaudoDiarioAsync(string NombreBanco, string IdCuentaBanco, string IdCuentaBancoEpicor, string RutaEntrada, string RutaSalida, object[] CorreosControl, string Remitente, string CodigoTransito, string NumCuenta, string TipoCuenta, string Usuario, string RutaProcesados, string TipoProceso) {
            this.ServicioRecaudoDiarioAsync(NombreBanco, IdCuentaBanco, IdCuentaBancoEpicor, RutaEntrada, RutaSalida, CorreosControl, Remitente, CodigoTransito, NumCuenta, TipoCuenta, Usuario, RutaProcesados, TipoProceso, null);
        }
        
        /// <remarks/>
        public void ServicioRecaudoDiarioAsync(string NombreBanco, string IdCuentaBanco, string IdCuentaBancoEpicor, string RutaEntrada, string RutaSalida, object[] CorreosControl, string Remitente, string CodigoTransito, string NumCuenta, string TipoCuenta, string Usuario, string RutaProcesados, string TipoProceso, object userState) {
            if ((this.ServicioRecaudoDiarioOperationCompleted == null)) {
                this.ServicioRecaudoDiarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServicioRecaudoDiarioOperationCompleted);
            }
            this.InvokeAsync("ServicioRecaudoDiario", new object[] {
                        NombreBanco,
                        IdCuentaBanco,
                        IdCuentaBancoEpicor,
                        RutaEntrada,
                        RutaSalida,
                        CorreosControl,
                        Remitente,
                        CodigoTransito,
                        NumCuenta,
                        TipoCuenta,
                        Usuario,
                        RutaProcesados,
                        TipoProceso}, this.ServicioRecaudoDiarioOperationCompleted, userState);
        }
        
        private void OnServicioRecaudoDiarioOperationCompleted(object arg) {
            if ((this.ServicioRecaudoDiarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServicioRecaudoDiarioCompleted(this, new ServicioRecaudoDiarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ServicioRecaudoDiarioCompletedEventHandler(object sender, ServicioRecaudoDiarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServicioRecaudoDiarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServicioRecaudoDiarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591