//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Procesos.PS.ServicioTarjetaCredito {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ITarjetasCredito", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class TarjetasCredito : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ServicioTarjetasCreditoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TarjetasCredito() {
            this.Url = global::Procesos.PS.Properties.Settings.Default.Procesos_PS_ServicioTarjetaCredito_TarjetasCredito;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ServicioTarjetasCreditoCompletedEventHandler ServicioTarjetasCreditoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITarjetasCredito/ServicioTarjetasCredito", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServicioTarjetasCredito([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string NombreBanco, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string IdCuentaBanco, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string IdCuentaBancoEpicor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RutaEntrada, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RutaSalida, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] object[] CorreosControl, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Remitente, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string CodigoTransito, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string NumCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TipoCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RutaProcesado, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TipoProceso) {
            object[] results = this.Invoke("ServicioTarjetasCredito", new object[] {
                        NombreBanco,
                        IdCuentaBanco,
                        IdCuentaBancoEpicor,
                        RutaEntrada,
                        RutaSalida,
                        CorreosControl,
                        Remitente,
                        CodigoTransito,
                        NumCuenta,
                        TipoCuenta,
                        Usuario,
                        RutaProcesado,
                        TipoProceso});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ServicioTarjetasCreditoAsync(string NombreBanco, string IdCuentaBanco, string IdCuentaBancoEpicor, string RutaEntrada, string RutaSalida, object[] CorreosControl, string Remitente, string CodigoTransito, string NumCuenta, string TipoCuenta, string Usuario, string RutaProcesado, string TipoProceso) {
            this.ServicioTarjetasCreditoAsync(NombreBanco, IdCuentaBanco, IdCuentaBancoEpicor, RutaEntrada, RutaSalida, CorreosControl, Remitente, CodigoTransito, NumCuenta, TipoCuenta, Usuario, RutaProcesado, TipoProceso, null);
        }
        
        /// <remarks/>
        public void ServicioTarjetasCreditoAsync(string NombreBanco, string IdCuentaBanco, string IdCuentaBancoEpicor, string RutaEntrada, string RutaSalida, object[] CorreosControl, string Remitente, string CodigoTransito, string NumCuenta, string TipoCuenta, string Usuario, string RutaProcesado, string TipoProceso, object userState) {
            if ((this.ServicioTarjetasCreditoOperationCompleted == null)) {
                this.ServicioTarjetasCreditoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServicioTarjetasCreditoOperationCompleted);
            }
            this.InvokeAsync("ServicioTarjetasCredito", new object[] {
                        NombreBanco,
                        IdCuentaBanco,
                        IdCuentaBancoEpicor,
                        RutaEntrada,
                        RutaSalida,
                        CorreosControl,
                        Remitente,
                        CodigoTransito,
                        NumCuenta,
                        TipoCuenta,
                        Usuario,
                        RutaProcesado,
                        TipoProceso}, this.ServicioTarjetasCreditoOperationCompleted, userState);
        }
        
        private void OnServicioTarjetasCreditoOperationCompleted(object arg) {
            if ((this.ServicioTarjetasCreditoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServicioTarjetasCreditoCompleted(this, new ServicioTarjetasCreditoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ServicioTarjetasCreditoCompletedEventHandler(object sender, ServicioTarjetasCreditoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServicioTarjetasCreditoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServicioTarjetasCreditoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591