//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Procesos.PS.ServicioBancos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWBancos", Namespace="http://tempuri.org/")]
    public partial class WsBancos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LecturaPagosOperationCompleted;
        
        private System.Threading.SendOrPostCallback PagosTarjetaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsBancos() {
            this.Url = global::Procesos.PS.Properties.Settings.Default.Procesos_PS_ServicioBancos_WsBancos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LecturaPagosCompletedEventHandler LecturaPagosCompleted;
        
        /// <remarks/>
        public event PagosTarjetaCompletedEventHandler PagosTarjetaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWBancos/LecturaPagos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LecturaPagos([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pasword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RutaArchivo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string NombreArchivo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string PagosOnline) {
            object[] results = this.Invoke("LecturaPagos", new object[] {
                        usuario,
                        pasword,
                        RutaArchivo,
                        NombreArchivo,
                        PagosOnline});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LecturaPagosAsync(string usuario, string pasword, string RutaArchivo, string NombreArchivo, string PagosOnline) {
            this.LecturaPagosAsync(usuario, pasword, RutaArchivo, NombreArchivo, PagosOnline, null);
        }
        
        /// <remarks/>
        public void LecturaPagosAsync(string usuario, string pasword, string RutaArchivo, string NombreArchivo, string PagosOnline, object userState) {
            if ((this.LecturaPagosOperationCompleted == null)) {
                this.LecturaPagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLecturaPagosOperationCompleted);
            }
            this.InvokeAsync("LecturaPagos", new object[] {
                        usuario,
                        pasword,
                        RutaArchivo,
                        NombreArchivo,
                        PagosOnline}, this.LecturaPagosOperationCompleted, userState);
        }
        
        private void OnLecturaPagosOperationCompleted(object arg) {
            if ((this.LecturaPagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LecturaPagosCompleted(this, new LecturaPagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWBancos/PagosTarjeta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PagosTarjeta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RutaArchivo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string NombreArchivo) {
            object[] results = this.Invoke("PagosTarjeta", new object[] {
                        usuario,
                        password,
                        RutaArchivo,
                        NombreArchivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PagosTarjetaAsync(string usuario, string password, string RutaArchivo, string NombreArchivo) {
            this.PagosTarjetaAsync(usuario, password, RutaArchivo, NombreArchivo, null);
        }
        
        /// <remarks/>
        public void PagosTarjetaAsync(string usuario, string password, string RutaArchivo, string NombreArchivo, object userState) {
            if ((this.PagosTarjetaOperationCompleted == null)) {
                this.PagosTarjetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPagosTarjetaOperationCompleted);
            }
            this.InvokeAsync("PagosTarjeta", new object[] {
                        usuario,
                        password,
                        RutaArchivo,
                        NombreArchivo}, this.PagosTarjetaOperationCompleted, userState);
        }
        
        private void OnPagosTarjetaOperationCompleted(object arg) {
            if ((this.PagosTarjetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PagosTarjetaCompleted(this, new PagosTarjetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LecturaPagosCompletedEventHandler(object sender, LecturaPagosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LecturaPagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LecturaPagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PagosTarjetaCompletedEventHandler(object sender, PagosTarjetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PagosTarjetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PagosTarjetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591