//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procesos.PS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.20.40:100/Bancos/Servicios/AsoBancaria.svc")]
        public string Procesos_PS_ServicioAsoBancaria_AsoBancaria {
            get {
                return ((string)(this["Procesos_PS_ServicioAsoBancaria_AsoBancaria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sbogche016v/AdministracionFtp/Servicios/moverArchivosFTP.svc")]
        public string Procesos_PS_MoverArchivosFTP_moverArchivosFTP {
            get {
                return ((string)(this["Procesos_PS_MoverArchivosFTP_moverArchivosFTP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51647/Servicios/PagosOnline.svc")]
        public string Procesos_PS_ServicioPagosOnline_PagosOnline {
            get {
                return ((string)(this["Procesos_PS_ServicioPagosOnline_PagosOnline"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sbogche016v/Bancos/Servicios/Recaudo.svc")]
        public string Procesos_PS_ServicioRecaudo_Recaudo {
            get {
                return ((string)(this["Procesos_PS_ServicioRecaudo_Recaudo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:51647/Servicios/TarjetasCredito.svc")]
        public string Procesos_PS_ServicioTarjetaCredito_TarjetasCredito {
            get {
                return ((string)(this["Procesos_PS_ServicioTarjetaCredito_TarjetasCredito"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sbogche010f/Administracionftp/Servicios/moverArchivosFTP.svc")]
        public string Procesos_PS_ServicioMoverArchivosFTP_moverArchivosFTP {
            get {
                return ((string)(this["Procesos_PS_ServicioMoverArchivosFTP_moverArchivosFTP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wsenviocorreos.chevyplan.col/service.asmx")]
        public string Procesos_PS_wsenviocorreos_Service {
            get {
                return ((string)(this["Procesos_PS_wsenviocorreos_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8090/WsBancos.svc")]
        public string Procesos_PS_ServicioBancos_WsBancos {
            get {
                return ((string)(this["Procesos_PS_ServicioBancos_WsBancos"]));
            }
        }
    }
}
